# Netlify 설정 파일

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true" 

# Netlify 함수(Functions) 설정 추가
[functions]
  external_node_modules = ["@netlify/plugin-nextjs"]
